os: Visual Studio 2015

environment:
  matrix:

  # Stable 64-bit MSVC
    - channel: stable
      target: x86_64-pc-windows-msvc
  # Stable 32-bit MSVC
    - channel: stable
      target: i686-pc-windows-msvc
  # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc
      #cargoflags: --features "unstable"
  # Nightly 32-bit MSVC
    - channel: nightly
      target: i686-pc-windows-msvc
      #cargoflags: --features "unstable"

# ### GNU Toolchains ###

#   # Stable 64-bit GNU
#     - channel: stable
#       target: x86_64-pc-windows-gnu
#   # Stable 32-bit GNU
#     - channel: stable
#       target: i686-pc-windows-gnu
#   # Beta 64-bit GNU
#     - channel: beta
#       target: x86_64-pc-windows-gnu
#   # Beta 32-bit GNU
#     - channel: beta
#       target: i686-pc-windows-gnu
#   # Nightly 64-bit GNU
#     - channel: nightly
#       target: x86_64-pc-windows-gnu
#       #cargoflags: --features "unstable"
#   # Nightly 32-bit GNU
#     - channel: nightly
#       target: i686-pc-windows-gnu
#       #cargoflags: --features "unstable"

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - git submodule update --init --recursive
  - cargo test --verbose --all %cargoflags%
  - cargo test --verbose --all --no-default-features %cargoflags%
  - cargo test --release --verbose --all %cargoflags%
  - cargo test --release --verbose --all --no-default-features %cargoflags%